ERROR at tests/data/invalid/references_self_in_family.ck 1:16-1:23: Could not resolve name 'Invalid'.